import IMG1 from './assets/gallery/marble.jpeg'

// --- 6 projects
const Data = [
  {
    id: 1,
    image: IMG1,
    title: 'Project title: ',
    description: 'project description and the technologies used',
    github: 'https://github.com',
    demo: 'https://netlify.com',
  },
  {
    id: 2,
    image: IMG1,
    title: 'Project title: ',
    description: 'project description and the technologies used',
    github: 'https://github.com',
    demo: 'https://netlify.com',
  },
  {
    id: 3,
    image: IMG1,
    title: 'Project title: ',
    description: 'project description and the technologies used',
    github: 'https://github.com',
    demo: 'https://netlify.com',
  },
  {
    id: 4,
    image: IMG1,
    title: 'Project title: ',
    description: 'project description and the technologies used',
    github: 'https://github.com',
    demo: 'https://netlify.com',
  },
  {
    id: 5,
    image: IMG1,
    title: 'Project title: ',
    description: 'project description and the technologies used',
    github: 'https://github.com',
    demo: 'https://netlify.com',
  },
  {
    id: 6,
    image: IMG1,
    title: 'Project title: ',
    description: 'project description and the technologies used',
    github: 'https://github.com',
    demo: 'https://netlify.com',
  },
]
///   9 projects ---
// const Data = [
//   {
//     id: 1,
//     image: IMG1,
//     title: 'Project title: ',
//     description: 'project description and the technologies used',
//     github: 'https://github.com',
//     demo: 'https://netlify.com',
//   },
//   {
//     id: 2,
//     image: IMG1,
//     title: 'Project title: ',
//     description: 'project description and the technologies used',
//     github: 'https://github.com',
//     demo: 'https://netlify.com',
//   },
//   {
//     id: 3,
//     image: IMG1,
//     title: 'Project title: ',
//     description: 'project description and the technologies used',
//     github: 'https://github.com',
//     demo: 'https://netlify.com',
//   },
//   {
//     id: 4,
//     image: IMG1,
//     title: 'Project title: ',
//     description: 'project description and the technologies used',
//     github: 'https://github.com',
//     demo: 'https://netlify.com',
//   },
//   {
//     id: 5,
//     image: IMG1,
//     title: 'Project title: ',
//     description: 'project description and the technologies used',
//     github: 'https://github.com',
//     demo: 'https://netlify.com',
//   },
//   {
//     id: 6,
//     image: IMG1,
//     title: 'Project title: ',
//     description: 'project description and the technologies used',
//     github: 'https://github.com',
//     demo: 'https://netlify.com',
//   },
//   {
//     id: 7,
//     image: IMG1,
//     title: 'Project title: ',
//     description: 'project description and the technologies used',
//     github: 'https://github.com',
//     demo: 'https://netlify.com',
//   },
//   {
//     id: 8,
//     image: IMG1,
//     title: 'Project title: ',
//     description: 'project description and the technologies used',
//     github: 'https://github.com',
//     demo: 'https://netlify.com',
//   },
//   {
//     id: 9,
//     image: IMG1,
//     title: 'Project title: ',
//     description: 'project description and the technologies used',
//     github: 'https://github.com',
//     demo: 'https://netlify.com',
//   },
// ]

export default Data
